# Generated by Django 4.2.16 on 2025-02-18 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiling", "0005_auto_20211018_2158"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilingupload",
            name="profiling_commit",
        ),
        migrations.DeleteModel(
            name="ProfilingCommit",
        ),
        migrations.DeleteModel(
            name="ProfilingUpload",
        ),
    ]
