# Generated by Django 4.2.16 on 2025-03-31 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiling", "0005_auto_20211018_2158"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfilingUpload",
        ),
        migrations.DeleteModel(
            name="ProfilingCommit",
        ),
    ]
