# Generated by Django 4.2.16 on 2025-02-06 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeseries", "0016_testrun_summary_1day"),
    ]

    operations = [
        migrations.RunSQL(
            """
            select add_continuous_aggregate_policy(
                'timeseries_testrun_summary_1day',
                start_offset => '7 days',
                end_offset => '1 days',
                schedule_interval => INTERVAL '1 days'
            );
            """,
            reverse_sql="select remove_continuous_aggregate_policy('timeseries_testrun_summary_1day');",
        ),
        migrations.RunSQL(
            """
            select add_continuous_aggregate_policy(
                'timeseries_testrun_branch_summary_1day',
                start_offset => '7 days',
                end_offset => '1 days',
                schedule_interval => INTERVAL '1 days'
            );
            """,
            reverse_sql="select remove_continuous_aggregate_policy('timeseries_testrun_branch_summary_1day');",
        ),
    ]
