# Generated by Django 4.2.16 on 2025-02-12 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeseries", "0018_testrun_summary_model"),
    ]

    operations = [
        migrations.RunSQL(
            """
                alter materialized view timeseries_testrun_summary_1day set (timescaledb.materialized_only = true);
                """
        )
        if not settings.TIMESERIES_REAL_TIME_AGGREGATES
        else migrations.RunSQL(
            """
                alter materialized view timeseries_testrun_summary_1day set (timescaledb.materialized_only = false);
                """
        ),
        migrations.RunSQL(
            """
                alter materialized view timeseries_testrun_branch_summary_1day set (timescaledb.materialized_only = true);
                """
        )
        if not settings.TIMESERIES_REAL_TIME_AGGREGATES
        else migrations.RunSQL(
            """
                alter materialized view timeseries_testrun_branch_summary_1day set (timescaledb.materialized_only = false);
                """
        ),
    ]
