codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
ignore:
  - conftest.py
  - "**/conftest.py"
  - "**tests**/test_*.py"
  - "tests**"

beta_groups:
  - "labels"

flag_management:
  individual_flags:
    - name: "smart-labels"
      carryforward: true
      carryforward_mode: "labels"

test_analytics:
  flake_detection: true
