# Generated by Django 4.2.16 on 2025-01-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flake",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("repoid", models.IntegerField()),
                ("test_id", models.BinaryField()),
                ("recent_passes_count", models.IntegerField()),
                ("count", models.IntegerField()),
                ("fail_count", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "test_analytics_flake",
                "indexes": [
                    models.Index(
                        fields=["repoid"], name="test_analyt_repoid_fcd881_idx"
                    ),
                    models.Index(
                        fields=["test_id"], name="test_analyt_test_id_f504a1_idx"
                    ),
                    models.Index(
                        fields=["repoid", "test_id"],
                        name="test_analyt_repoid_0690c3_idx",
                    ),
                    models.Index(
                        fields=["repoid", "end_date"],
                        name="test_analyt_repoid_9e2402_idx",
                    ),
                ],
            },
        ),
    ]
