# Generated by Django 4.2.16 on 2025-01-20 17:38

from django.db import migrations, models

"""
BEGIN;
--
-- Add field flags_id to flake
--
ALTER TABLE "test_analytics_flake" ADD COLUMN "flags_id" bytea NULL;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("test_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flake",
            name="flags_id",
            field=models.BinaryField(null=True),
        ),
    ]
