# Generated by Django 4.2.6 on 2023-11-01 21:00
# Modified by hand to suit timeseries data

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimpleMetric",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                ("repo_id", models.BigIntegerField(null=True)),
                ("owner_id", models.BigIntegerField(null=True)),
                ("commit_id", models.BigIntegerField(null=True)),
                ("name", models.TextField()),
                ("value", models.FloatField()),
            ],
            options={
                "db_table": "telemetry_simple",
                "abstract": False,
            },
        ),
        # Django wants us to have a primary key. Closest we have is `timestamp`,
        # but it isn't necessarily unique, so we drop the pkey constraint.
        migrations.RunSQL(
            "ALTER TABLE telemetry_simple DROP CONSTRAINT telemetry_simple_pkey;",
            reverse_sql="",
        ),
        migrations.AddIndex(
            model_name="SimpleMetric",
            index=models.Index(
                fields=[
                    "name",
                    "timestamp",
                    "repo_id",
                    "owner_id",
                    "commit_id",
                ],
                name="telemetry_s_name_23f8a7_idx",
            ),
        ),
    ]

    if hasattr(settings, "TEST") and settings.TEST:
        # Skip steps that complicate tests
        operations = [operations[0], operations[2]]
