# Generated by Django 4.2.16 on 2025-03-12 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pg_telemetry", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimpleMetric",
        ),
    ]
