# Generated by Django 4.2.3 on 2023-09-19 20:52

from django.db import migrations, models

from shared.django_apps.core.models import DateTimeWithoutTZField


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0043_sync_user_terms_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="terms_agreement",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="terms_agreement_at",
            field=DateTimeWithoutTZField(blank=True, null=True),
        ),
    ]
