# Generated by Django 5.0.3 on 2024-03-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0053_ownerinstallationnametousefortask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="fake_field",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
