# Generated by Django 4.2.11 on 2024-04-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0054_update_owners_column_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='random_field_auth',
            field=models.IntegerField(null=True),
        ),
    ]
