# Generated by Django 4.2.11 on 2024-04-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field login_session to session
    --
    ALTER TABLE "sessions" ADD COLUMN "login_session_id" varchar(40) NULL CONSTRAINT "sessions_login_session_id_4c8453b4_fk_django_se" REFERENCES "django_session"("session_key") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "sessions_login_session_id_4c8453b4_fk_django_se" IMMEDIATE;
    CREATE INDEX "sessions_login_session_id_4c8453b4" ON "sessions" ("login_session_id");
    CREATE INDEX "sessions_login_session_id_4c8453b4_like" ON "sessions" ("login_session_id" varchar_pattern_ops);
    COMMIT;
    """

    dependencies = [
        ("sessions", "0001_initial"),
        ("codecov_auth", "0054_update_owners_column_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="login_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sessions.session",
            ),
        ),
    ]
