# Generated by Django 4.2.11 on 2024-04-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('codecov_auth', '0055_owner_random_field_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='login_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
