# Generated by Django 4.2.13 on 2024-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0055_session_login_session"),
    ]

    # BEGIN;
    # --
    # -- Add field is_suspended to githubappinstallation
    # --
    # ALTER TABLE "codecov_auth_githubappinstallation" ADD COLUMN "is_suspended" boolean DEFAULT false NOT NULL;
    # ALTER TABLE "codecov_auth_githubappinstallation" ALTER COLUMN "is_suspended" DROP DEFAULT;
    # COMMIT;

    operations = [
        migrations.AddField(
            model_name="githubappinstallation",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
    ]
