# Generated by Django 4.2.13 on 2024-06-18 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0056_githubappinstallation_is_suspended"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(blank=True, default=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("users-basic", "BASIC_PLAN_NAME"),
                            ("users-trial", "TRIAL_PLAN_NAME"),
                            ("users-pr-inappm", "CODECOV_PRO_MONTHLY"),
                            ("users-pr-inappy", "CODECOV_PRO_YEARLY"),
                            ("users-sentrym", "SENTRY_MONTHLY"),
                            ("users-sentryy", "SENTRY_YEARLY"),
                            ("users-teamm", "TEAM_MONTHLY"),
                            ("users-teamy", "TEAM_YEARLY"),
                            ("users", "GHM_PLAN_NAME"),
                            ("users-free", "FREE_PLAN_NAME"),
                            ("users-inappm", "CODECOV_PRO_MONTHLY_LEGACY"),
                            ("users-inappy", "CODECOV_PRO_YEARLY_LEGACY"),
                            ("users-enterprisem", "ENTERPRISE_CLOUD_MONTHLY"),
                            ("users-enterprisey", "ENTERPRISE_CLOUD_YEARLY"),
                        ],
                        default="users-basic",
                        max_length=50,
                    ),
                ),
                ("plan_seat_count", models.SmallIntegerField(blank=True, default=1)),
                ("free_seat_count", models.SmallIntegerField(blank=True, default=0)),
                ("plan_auto_activate", models.BooleanField(blank=True, default=True)),
                ("is_delinquent", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeBilling",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_id", models.CharField(max_length=255, unique=True)),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(blank=True, default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_billing",
                        to="codecov_auth.account",
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OktaSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(blank=True, default=True)),
                ("enforced", models.BooleanField(blank=True, default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="okta_settings",
                        to="codecov_auth.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceBilling",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_manager",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("invoice_notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_billing",
                        to="codecov_auth.account",
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountsUsers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="codecov_auth.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "account")},
            },
        ),
        migrations.AddField(
            model_name="account",
            name="users",
            field=models.ManyToManyField(
                related_name="accounts",
                through="codecov_auth.AccountsUsers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
