# Generated by Django 4.2.13 on 2024-06-25 18:19

import django.db.models.deletion
from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddField


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field account to owner
    --
    ALTER TABLE "owners" ADD COLUMN "account_id" bigint NULL CONSTRAINT "owners_account_id_850ef729_fk_codecov_auth_account_id" REFERENCES "codecov_auth_account"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "owners_account_id_850ef729_fk_codecov_auth_account_id" IMMEDIATE;
    CREATE INDEX "owners_account_id_850ef729" ON "owners" ("account_id");
    COMMIT;
    """

    dependencies = [
        (
            "codecov_auth",
            "0057_account_stripebilling_oktasettings_invoicebilling_and_more",
        ),
    ]

    operations = [
        RiskyAddField(
            model_name="owner",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="codecov_auth.account",
            ),
        ),
    ]
