# Generated by Django 4.2.14 on 2024-07-30 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0058_owner_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountsusers",
            options={"verbose_name_plural": "Accounts Users"},
        ),
    ]
