# Generated by Django 4.2.16 on 2024-09-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0059_alter_accountsusers_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="upload_token_required_for_public_repos",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
