# Generated by Django 4.2.16 on 2024-09-26 22:53

from django.db import migrations


def backfill_upload_token_required_for_public_repos(apps, _):
    Owner = apps.get_model("codecov_auth", "Owner")
    n_updated = Owner.objects.filter(
        upload_token_required_for_public_repos__isnull=True
    ).update(upload_token_required_for_public_repos=True)
    return n_updated


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0060_owner_upload_token_required_for_public_repos"),
    ]

    operations = [
        migrations.RunPython(
            backfill_upload_token_required_for_public_repos,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
