# Generated by Django 4.2.16 on 2024-10-01 23:40

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRunPython


def backfill_upload_token_required_for_public_repos(apps, _):
    Owner = apps.get_model("codecov_auth", "Owner")
    n_updated = Owner.objects.exclude(
        upload_token_required_for_public_repos=True
    ).update(upload_token_required_for_public_repos=True)
    return n_updated


class Migration(migrations.Migration):
    """
    NO SQL COUNTERPART REQUIRED
    """

    dependencies = [
        ("codecov_auth", "0060_owner_upload_token_required_for_public_repos"),
    ]

    operations = [
        RiskyRunPython(
            backfill_upload_token_required_for_public_repos,
            reverse_code=migrations.RunPython.noop,
        )
    ]
