# Generated by Django 4.2.16 on 2024-09-26 22:53

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyRunPython, RiskyAlterField


def backfill_upload_token_required_for_public_repos(apps, _):
    Owner = apps.get_model("codecov_auth", "Owner")
    n_updated = Owner.objects.filter(
        upload_token_required_for_public_repos__isnull=True
    ).update(upload_token_required_for_public_repos=True)
    return n_updated


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Alter field upload_token_required_for_public_repos on owner
    --
    UPDATE "owners" SET "upload_token_required_for_public_repos" = true WHERE "upload_token_required_for_public_repos" IS NULL; SET CONSTRAINTS ALL IMMEDIATE;
    ALTER TABLE "owners" ALTER COLUMN "upload_token_required_for_public_repos" SET NOT NULL;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0060_owner_upload_token_required_for_public_repos"),
    ]

    operations = [
        RiskyRunPython(
            backfill_upload_token_required_for_public_repos,
            reverse_code=migrations.RunPython.noop,
        ),
        RiskyAlterField(
            model_name="owner",
            name="upload_token_required_for_public_repos",
            field=models.BooleanField(default=False),
        ),
    ]
