# Generated by Django 4.2.16 on 2024-09-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0061_backfill_upload_token_required_for_public_repos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="upload_token_required_for_public_repos",
            field=models.BooleanField(default=False),
        ),
    ]
