# Generated by Django 4.2.16 on 2024-10-01 23:49

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAlterField


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Alter field upload_token_required_for_public_repos on owner
    --
    UPDATE "owners" SET "upload_token_required_for_public_repos" = true WHERE "upload_token_required_for_public_repos" IS NULL; SET CONSTRAINTS ALL IMMEDIATE;
    ALTER TABLE "owners" ALTER COLUMN "upload_token_required_for_public_repos" SET NOT NULL;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0061_backfill_upload_token_required_for_public_repos"),
    ]

    operations = [
        RiskyAlterField(
            model_name="owner",
            name="upload_token_required_for_public_repos",
            field=models.BooleanField(default=False),
        ),
    ]
