# Generated by Django 4.2.16 on 2025-01-14 18:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create model Tier
    --
    CREATE TABLE "codecov_auth_tier" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "tier_name" varchar(255) NOT NULL UNIQUE, "bundle_analysis" boolean NOT NULL, "test_analytics" boolean NOT NULL, "flaky_test_detection" boolean NOT NULL, "project_coverage" boolean NOT NULL, "private_repo_support" boolean NOT NULL);
    --
    -- Create model Plan
    --
    CREATE TABLE "codecov_auth_plan" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "base_unit_price" integer NOT NULL, "benefits" text[] NOT NULL, "billing_rate" text NULL, "is_active" boolean NOT NULL, "marketing_name" varchar(255) NOT NULL, "max_seats" integer NULL, "monthly_uploads_limit" integer NULL, "paid_plan" boolean NOT NULL, "name" varchar(255) NOT NULL UNIQUE, "tier_id" bigint NOT NULL);
    CREATE INDEX "codecov_auth_tier_tier_name_ec8e98b1_like" ON "codecov_auth_tier" ("tier_name" varchar_pattern_ops);
    ALTER TABLE "codecov_auth_plan" ADD CONSTRAINT "codecov_auth_plan_tier_id_7847a9eb_fk_codecov_auth_tier_id" FOREIGN KEY ("tier_id") REFERENCES "codecov_auth_tier" ("id") DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX "codecov_auth_plan_name_e2fccac6_like" ON "codecov_auth_plan" ("name" varchar_pattern_ops);
    CREATE INDEX "codecov_auth_plan_tier_id_7847a9eb" ON "codecov_auth_plan" ("tier_id");
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0062_alter_owner_upload_token_required_for_public_repos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tier_name", models.CharField(max_length=255, unique=True)),
                ("bundle_analysis", models.BooleanField(default=False)),
                ("test_analytics", models.BooleanField(default=False)),
                ("flaky_test_detection", models.BooleanField(default=False)),
                ("project_coverage", models.BooleanField(default=False)),
                ("private_repo_support", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_unit_price", models.IntegerField(blank=True, default=0)),
                (
                    "benefits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "billing_rate",
                    models.TextField(
                        blank=True,
                        choices=[("monthly", "Monthly"), ("annually", "Annually")],
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("marketing_name", models.CharField(max_length=255)),
                ("max_seats", models.IntegerField(blank=True, null=True)),
                ("monthly_uploads_limit", models.IntegerField(blank=True, null=True)),
                ("paid_plan", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="codecov_auth.tier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
