# Generated by Django 4.2.16 on 2025-01-31 09:35

from django.db import migrations


def add_pro_plan(apps, schema_editor):
    Plan = apps.get_model("codecov_auth", "Plan")
    Tier = apps.get_model("codecov_auth", "Tier")

    # Get the 'Pro' tier
    pro_tier = Tier.objects.get(tier_name="Pro")

    # Create a new plan
    Plan.objects.create(
        tier=pro_tier,
        base_unit_price=10,
        benefits=[
            "Configurable # of users",
            "Unlimited public repositories",
            "Unlimited private repositories",
            "Priority Support",
        ],
        billing_rate="annually",  # Set the billing rate
        is_active=True,
        marketing_name="Pro",
        max_seats=None,  # Set the max seats
        monthly_uploads_limit=None,  # Set the monthly uploads limit
        name="users-pr-inappy",
        paid_plan=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0064_plan_stripe_id"),
    ]

    operations = [
        migrations.RunPython(add_pro_plan),
    ]
