# Generated by Django 4.2.16 on 2025-01-30 13:24

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Alter field plan on account
    --
    -- (no-op)
    --
    -- Raw SQL operation
    --
    ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-developer';
    --
    -- Alter field plan on owner
    --
    -- (no-op)
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0064_plan_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="plan",
            field=models.CharField(
                choices=[
                    ("users-basic", "BASIC_PLAN_NAME"),
                    ("users-trial", "TRIAL_PLAN_NAME"),
                    ("users-pr-inappm", "CODECOV_PRO_MONTHLY"),
                    ("users-pr-inappy", "CODECOV_PRO_YEARLY"),
                    ("users-sentrym", "SENTRY_MONTHLY"),
                    ("users-sentryy", "SENTRY_YEARLY"),
                    ("users-teamm", "TEAM_MONTHLY"),
                    ("users-teamy", "TEAM_YEARLY"),
                    ("users", "GHM_PLAN_NAME"),
                    ("users-free", "FREE_PLAN_NAME"),
                    ("users-inappm", "CODECOV_PRO_MONTHLY_LEGACY"),
                    ("users-inappy", "CODECOV_PRO_YEARLY_LEGACY"),
                    ("users-enterprisem", "ENTERPRISE_CLOUD_MONTHLY"),
                    ("users-enterprisey", "ENTERPRISE_CLOUD_YEARLY"),
                    ("users-developer", "USERS_DEVELOPER"),
                ],
                default="users-developer",
                max_length=50,
            ),
        ),
        RiskyRunSQL("ALTER TYPE plans ADD VALUE 'users-developer';"),
        migrations.AlterField(
            model_name="owner",
            name="plan",
            field=models.TextField(blank=True, default="users-developer", null=True),
        ),
    ]
