# Generated by Django 4.2.16 on 2025-02-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0066_add_pro_plan"),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE owners ALTER COLUMN plan DROP DEFAULT;"),
        migrations.AlterField(
            model_name="owner",
            name="plan",
            field=models.TextField(blank=True, default="users-developer"),
        ),
    ]
