# Generated by Django 4.2.11 on 2024-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_increment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='test_value_core',
            field=models.TextField(null=True),
        ),
    ]
