# Generated by Django 4.2.11 on 2024-04-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_increment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='random_field_pulls',
            field=models.IntegerField(null=True),
        ),
    ]
