# Generated by Django 4.2.13 on 2024-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field tests_enabled to repository
    --
    ALTER TABLE "repos" ADD COLUMN "tests_enabled" boolean DEFAULT false NULL;
    ALTER TABLE "repos" ALTER COLUMN "tests_enabled" DROP DEFAULT;
    COMMIT;
    """

    dependencies = [
        ("core", "0049_increment_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="tests_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
