# Generated by Django 4.2.13 on 2024-05-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0055_session_login_session"),
        ("core", "0049_increment_version"),
    ]

    # BEGIN;
    # --
    # -- Add field gh_app to commitnotification
    # --
    # ALTER TABLE "commit_notifications" ADD COLUMN "gh_app_id" bigint NULL CONSTRAINT "commit_notifications_gh_app_id_8714fedd_fk_codecov_a" REFERENCES "codecov_auth_githubappinstallation"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "commit_notifications_gh_app_id_8714fedd_fk_codecov_a" IMMEDIATE;
    # --
    # -- Alter field notification_type on commitnotification
    # --
    # -- (no-op)
    # CREATE INDEX "commit_notifications_gh_app_id_8714fedd" ON "commit_notifications" ("gh_app_id");
    # COMMIT;

    operations = [
        migrations.AddField(
            model_name="commitnotification",
            name="gh_app",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commit_notifications",
                to="codecov_auth.githubappinstallation",
            ),
        ),
        migrations.AlterField(
            model_name="commitnotification",
            name="notification_type",
            field=models.TextField(
                choices=[
                    ("comment", "Comment"),
                    ("gitter", "Gitter"),
                    ("hipchat", "Hipchat"),
                    ("irc", "Irc"),
                    ("slack", "Slack"),
                    ("status_changes", "Status Changes"),
                    ("status_patch", "Status Patch"),
                    ("status_project", "Status Project"),
                    ("webhook", "Webhook"),
                    ("codecov_slack_app", "Codecov Slack App"),
                    ("checks_project", "Checks Project"),
                    ("checks_changes", "Checks Changes"),
                    ("checks_patch", "Checks Patch"),
                ]
            ),
        ),
    ]
