# Generated by Django 4.2.13 on 2024-05-27 11:39

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAlterField


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field test_analytics_enabled to repository
    --
    ALTER TABLE "repos" ADD COLUMN "test_analytics_enabled" boolean DEFAULT false NULL;
    ALTER TABLE "repos" ALTER COLUMN "test_analytics_enabled" DROP DEFAULT;
    COMMIT;
    """

    dependencies = [
        ("core", "0049_increment_version"),
    ]

    operations = [
        RiskyAlterField(
            model_name="repository",
            name="test_analytics_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
