# Generated by Django 4.2.13 on 2024-06-03 18:44

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "24.6.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_repository_test_analytics_enabled"),
    ]

    operations = [migrations.RunPython(update_version)]
