# Generated by Django 4.2.13 on 2024-07-01 22:57

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "24.7.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
