# Generated by Django 4.2.13 on 2024-06-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_increment_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingLifeCycleMetrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orgid', models.IntegerField()),
                ('event', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
