# Generated by Django 4.2.14 on 2024-08-05 18:05

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "24.8.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_repository_branch"),
    ]

    operations = [migrations.RunPython(update_version)]
