# Generated by Django 4.2.14 on 2024-08-07 13:35

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations

from shared.django_apps.migration_utils import RiskyAddIndex


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create index name_trgm_idx on OpClass(Upper(F(name)), name=gin_trgm_ops) on model branch
    --
    CREATE INDEX "name_trgm_idx" ON "branches" USING gin ((UPPER("branch")) gin_trgm_ops);
    COMMIT;
    """

    dependencies = [
        ("core", "0055_increment_version"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="branch",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                ),
                name="name_trgm_idx",
            ),
        ),
    ]
