# Generated by Django 4.2.15 on 2024-08-29 20:08

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "24.9.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_branch_name_trgm_idx"),
    ]

    operations = [migrations.RunPython(update_version)]
