# Generated by Django 4.2.13 on 2024-08-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_branch_name_trgm_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
