# Generated by Django 4.2.16 on 2024-09-05 16:16

from django.db import migrations, models
from shared.django_apps.migration_utils import RiskyAddField


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_increment_version"),
    ]

    # BEGIN;
    # --
    # -- Add field ai_features_enabled to repository
    # --
    # ALTER TABLE "repos" ADD COLUMN "ai_features_enabled" boolean DEFAULT false NULL;
    # ALTER TABLE "repos" ALTER COLUMN "ai_features_enabled" DROP DEFAULT;
    # COMMIT;

    operations = [
        RiskyAddField(
            model_name="repository",
            name="ai_features_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
