# Generated by Django 4.2.16 on 2024-10-01 17:24

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "24.10.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
