# Generated by Django 4.2.16 on 2025-01-27 13:18

import django.db.models.deletion
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0063_increment_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="fork",
            field=models.ForeignKey(
                blank=True,
                db_column="forkid",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.repository",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        AddIndexConcurrently(
            model_name="commit",
            index=models.Index(fields=["author"], name="commits_author_cd2f50_idx"),
        ),
        AddIndexConcurrently(
            model_name="repository",
            index=models.Index(fields=["fork"], name="repos_forkid_4cd440_idx"),
        ),
    ]
