# Generated by Django 4.2.16 on 2025-02-03 19:18

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.2.3"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_missing_indices"),
    ]

    operations = [migrations.RunPython(update_version)]
