# Generated by Django 4.2.16 on 2025-02-07 20:22

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.2.7"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
