# Generated by Django 4.2.16 on 2025-04-01 16:38

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "25.4.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_increment_version"),
    ]

    operations = [migrations.RunPython(update_version)]
