# Generated by Django 4.2.16 on 2025-02-06 16:57
import django.contrib.postgres.fields
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ta_timeseries", "0003_testrun_cagg_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestrunSummary",
            fields=[
                (
                    "timestamp_bin",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("repo_id", models.IntegerField()),
                ("name", models.TextField()),
                ("classname", models.TextField()),
                ("testsuite", models.TextField()),
                ("computed_name", models.TextField()),
                ("failing_commits", models.IntegerField()),
                ("avg_duration_seconds", models.FloatField()),
                ("last_duration_seconds", models.FloatField()),
                ("pass_count", models.IntegerField()),
                ("fail_count", models.IntegerField()),
                ("skip_count", models.IntegerField()),
                ("flaky_fail_count", models.IntegerField()),
                ("updated_at", models.DateTimeField()),
                (
                    "flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
            ],
            options={
                "db_table": "ta_timeseries_testrun_summary_1day",
                "managed": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "ta_timeseries.testrun_summary"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TestrunBranchSummary",
            fields=[
                (
                    "timestamp_bin",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("repo_id", models.IntegerField()),
                ("branch", models.TextField()),
                ("name", models.TextField()),
                ("classname", models.TextField()),
                ("testsuite", models.TextField()),
                ("computed_name", models.TextField()),
                ("failing_commits", models.IntegerField()),
                ("avg_duration_seconds", models.FloatField()),
                ("last_duration_seconds", models.FloatField()),
                ("pass_count", models.IntegerField()),
                ("fail_count", models.IntegerField()),
                ("skip_count", models.IntegerField()),
                ("flaky_fail_count", models.IntegerField()),
                ("updated_at", models.DateTimeField()),
                (
                    "flags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
            ],
            options={
                "db_table": "ta_timeseries_testrun_branch_summary_1day",
                "managed": False,
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "ta_timeseries.testrun_branch_summary"
                ),
                models.Model,
            ),
        ),
    ]
