# Generated by Django 4.2.11 on 2024-04-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0017_testinstance_flaky_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinstance",
            name="branch",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="testinstance",
            name="commitid",
            field=models.TextField(null=True),
        ),
    ]
