# Generated by Django 4.2.11 on 2024-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_testinstance_flaky_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitreport',
            name='test_value_report',
            field=models.TextField(null=True),
        ),
    ]
