# Generated by Django 4.2.11 on 2024-04-24 16:02

from django.db import migrations
from migration_utils import RiskyRunPython



class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_remove_testinstance_flaky_status_test_flaky_and_more'),
    ]
    def populate_test_instances(apps, schema_editor):
        TestInstance = apps.get_model("reports", "TestInstance")

        test_instances = TestInstance.objects.select_related("upload__report__commit").all()
        for test_instance in test_instances:
            test_instance.branch = test_instance.upload.report.commit.branch
            test_instance.commitid = test_instance.upload.report.commit.commitid
        TestInstance.objects.bulk_update(test_instances, ["branch", "commitid"])


    operations = [
        RiskyRunPython(populate_test_instances)
    ]
