# Generated by Django 4.2.11 on 2024-05-21 13:57

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAlterField


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0019_auto_20240424_1824"),
    ]

    operations = [
        RiskyAlterField(
            model_name="reportleveltotals",
            name="coverage",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        RiskyAlterField(
            model_name="uploadleveltotals",
            name="coverage",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
