# Generated by Django 4.2.16 on 2024-09-09 14:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

"""
BEGIN;
--
-- Create model DailyTestTotals
--
CREATE TABLE "reports_dailytesttotals" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "date" date NOT NULL, "repoid" integer NOT NULL, "branch" text NOT NULL, "fail_count" integer NOT NULL, "pass_count" integer NOT NULL, "last_duration_seconds" double precision NOT NULL, "avg_duration_seconds" double precision NOT NULL, "latest_run" timestamp with time zone NOT NULL, "commits_where_fail" text[] NOT NULL, "test_id" text NOT NULL);
--
-- Create constraint reports_dailytesttotals_repoid_date_branch_test on model dailytesttotals
--
ALTER TABLE "reports_dailytesttotals" ADD CONSTRAINT "reports_dailytesttotals_repoid_date_branch_test" UNIQUE ("repoid", "date", "branch", "test_id");
ALTER TABLE "reports_dailytesttotals" ADD CONSTRAINT "reports_dailytesttotals_test_id_8046f5b2_fk_reports_test_id" FOREIGN KEY ("test_id") REFERENCES "reports_test" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reports_dailytesttotals_test_id_8046f5b2" ON "reports_dailytesttotals" ("test_id");
CREATE INDEX "reports_dailytesttotals_test_id_8046f5b2_like" ON "reports_dailytesttotals" ("test_id" text_pattern_ops);
CREATE INDEX "dailytesttotals_repoid_date" ON "reports_dailytesttotals" ("repoid", "date");
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0022_reducederror_flake_testinstance_reduced_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTestTotals",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("repoid", models.IntegerField()),
                ("branch", models.TextField()),
                ("fail_count", models.IntegerField()),
                ("pass_count", models.IntegerField()),
                ("last_duration_seconds", models.FloatField()),
                ("avg_duration_seconds", models.FloatField()),
                ("latest_run", models.DateTimeField()),
                (
                    "commits_where_fail",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_test_totals",
                        to="reports.test",
                    ),
                ),
            ],
            options={
                "db_table": "reports_dailytesttotals",
                "indexes": [
                    models.Index(
                        fields=["repoid", "date"], name="dailytesttotals_repoid_date"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailytesttotals",
            constraint=models.UniqueConstraint(
                fields=("repoid", "date", "branch", "test"),
                name="reports_dailytesttotals_repoid_date_branch_test",
            ),
        ),
    ]
