# Generated by Django 4.2.15 on 2024-09-09 19:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0022_reducederror_flake_testinstance_reduced_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTestRollup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("repoid", models.IntegerField()),
                ("branch", models.TextField()),
                ("fail_count", models.IntegerField()),
                ("pass_count", models.IntegerField()),
                ("last_duration_seconds", models.FloatField()),
                ("avg_duration_seconds", models.FloatField()),
                ("latest_run", models.DateTimeField()),
                (
                    "commits_where_fail",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_test_rollups",
                        to="reports.test",
                    ),
                ),
            ],
            options={
                "db_table": "reports_dailytestrollups",
                "indexes": [
                    models.Index(
                        fields=["repoid", "date"], name="dailytestrollups_repoid_date"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailytestrollup",
            constraint=models.UniqueConstraint(
                fields=("repoid", "date", "branch", "test"),
                name="reports_dailytestrollups_repoid_date_branch_test",
            ),
        ),
    ]
