# Generated by Django 4.2.15 on 2024-09-17 21:21

from django.db import migrations
from psqlextra.backend.migrations.operations import PostgresAddRangePartition

"""
BEGIN;
--
-- Creates range partition reports_dailytestrollups_2024_jul on DailyTestRollup
--
CREATE TABLE "reports_dailytestrollups_reports_dailytestrollups_2024_jul" PARTITION OF "reports_dailytestrollups" FOR VALUES FROM ('2024-07-01') TO ('2024-08-01');
--
-- Creates range partition reports_dailytestrollups_2024_aug on DailyTestRollup
--
CREATE TABLE "reports_dailytestrollups_reports_dailytestrollups_2024_aug" PARTITION OF "reports_dailytestrollups" FOR VALUES FROM ('2024-08-01') TO ('2024-09-01');
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0023_auto_20240909_2002"),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="DailyTestRollup",
            name="reports_dailytestrollups_2024_jul",
            from_values="2024-07-01",
            to_values="2024-08-01",
        ),
        PostgresAddRangePartition(
            model_name="DailyTestRollup",
            name="reports_dailytestrollups_2024_aug",
            from_values="2024-08-01",
            to_values="2024-09-01",
        ),
    ]
