# Generated by Django 4.2.15 on 2024-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20240909_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytestrollup',
            name='flaky_fail_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
