# Generated by Django 4.2.15 on 2024-09-12 21:11

from django.db import migrations, models

"""
BEGIN;
--
-- Add field flaky_fail_count to dailytestrollup
--
ALTER TABLE "reports_dailytestrollups" ADD COLUMN "flaky_fail_count" integer DEFAULT 0 NOT NULL;
ALTER TABLE "reports_dailytestrollups" ALTER COLUMN "flaky_fail_count" DROP DEFAULT;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0024_auto_20240917_2121"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailytestrollup",
            name="flaky_fail_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
