# Generated by Django 4.2.15 on 2024-10-15 16:42

"""
BEGIN;
--
-- Remove field commits_where_fail from test
--
ALTER TABLE "reports_test" DROP COLUMN "commits_where_fail" CASCADE;
--
-- Remove field failure_rate from test
--
ALTER TABLE "reports_test" DROP COLUMN "failure_rate" CASCADE;
COMMIT;
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0027_test_computed_name_test_filename_test_framework"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="commits_where_fail",
        ),
        migrations.RemoveField(
            model_name="test",
            name="failure_rate",
        ),
    ]
