# Generated by Django 4.2.15 on 2024-09-20 20:21

from django.db import migrations, models

"""
BEGIN;
--
-- Alter field branch on dailytestrollup
--
ALTER TABLE "reports_dailytestrollups" ALTER COLUMN "branch" DROP NOT NULL;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0027_test_computed_name_test_filename_test_framework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytestrollup",
            name="branch",
            field=models.TextField(null=True),
        ),
    ]
