# Generated by Django 4.2.15 on 2024-10-18 15:16

from django.db import migrations, models

"""
BEGIN;
--
-- Alter field duration_seconds on testinstance
--
ALTER TABLE "reports_testinstance" ALTER COLUMN "duration_seconds" DROP NOT NULL;
COMMIT;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_remove_test_commits_where_fail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='duration_seconds',
            field=models.FloatField(null=True),
        ),
    ]
