# Generated by Django 4.2.16 on 2024-11-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_increment_version"),
        ("reports", "0030_testflagbridge_reports_test_results_flag_bridge_flag_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastCacheRollupDate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("branch", models.TextField()),
                ("last_rollup_date", models.DateField()),
                (
                    "repository",
                    models.ForeignKey(
                        db_column="repoid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "reports_lastrollupdate",
            },
        ),
        migrations.AddConstraint(
            model_name="lastcacherollupdate",
            constraint=models.UniqueConstraint(
                fields=("repository", "branch"),
                name="reports_lastrollupdate_repoid_branch",
            ),
        ),
    ]
