# Generated by Django 4.2.16 on 2024-11-27 14:46

from django.db import migrations, models

"""
BEGIN;
--
-- Alter field duration_seconds on testinstance
--
ALTER TABLE "reports_testinstance" ALTER COLUMN "duration_seconds" DROP NOT NULL;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0032_reportsession_reports_upload_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testinstance",
            name="duration_seconds",
            field=models.FloatField(null=True),
        ),
    ]
