# Generated by Django 4.2.16 on 2024-11-28 12:26

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("reports", "0033_alter_testinstance_duration_seconds"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="reportsession",
            index=models.Index(
                name="upload_report_type_idx",
                fields=["report_id", "upload_type"],
            ),
        ),
    ]
