# Generated by Django 4.2.16 on 2024-12-13 15:44

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRemoveField

"""
BEGIN;
--
-- Remove field created_at from flake
--
ALTER TABLE "reports_flake" DROP COLUMN "created_at" CASCADE;
--
-- Remove field updated_at from flake
--
ALTER TABLE "reports_flake" DROP COLUMN "updated_at" CASCADE;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0033_alter_testinstance_duration_seconds"),
    ]

    operations = [
        RiskyRemoveField(
            model_name="flake",
            name="created_at",
        ),
        RiskyRemoveField(
            model_name="flake",
            name="updated_at",
        ),
    ]
