# Generated by Django 4.2.16 on 2024-12-30 14:55

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAlterField

"""
BEGIN;
--
-- Alter field storage_path on reportsession
--
ALTER TABLE "reports_upload" ALTER COLUMN "storage_path" DROP NOT NULL;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0034_remove_flake_created_at_remove_flake_updated_at"),
    ]

    operations = [
        RiskyAlterField(
            model_name="reportsession",
            name="storage_path",
            field=models.TextField(null=True),
        ),
    ]
