# Generated by Django 4.2.16 on 2025-01-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0035_upload_indices_part1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportsession",
            name="storage_path",
            field=models.TextField(null=True),
        ),
    ]
