# Generated by Django 4.2.16 on 2025-01-09 11:53

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models

import shared.django_apps.reports.compare


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_increment_version"),
        ("reports", "0035_upload_indices_part1"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompareCommit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_storage_path", models.CharField(max_length=150, null=True)),
                ("patch_totals", models.JSONField(null=True)),
                ("state", models.TextField()),
                ("error", models.TextField(null=True)),
                (
                    "base_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.commit",
                    ),
                ),
                (
                    "compare_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.commit",
                    ),
                ),
            ],
            options={
                "db_table": "compare_commitcomparison",
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "reports.compare_commitcomparison"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CompareFlag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("head_totals", models.JSONField(null=True)),
                ("base_totals", models.JSONField(null=True)),
                ("patch_totals", models.JSONField(null=True)),
                (
                    "commit_comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.comparecommit",
                    ),
                ),
                (
                    "repositoryflag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.repositoryflag",
                    ),
                ),
            ],
            options={
                "db_table": "compare_flagcomparison",
                "indexes": [
                    shared.django_apps.reports.compare.LongIndex(
                        fields=["commit_comparison_id"],
                        name="compare_flagcomparison_commit_comparison_id_88fa76fe",
                    ),
                    shared.django_apps.reports.compare.LongIndex(
                        fields=["repositoryflag_id"],
                        name="compare_flagcomparison_repositoryflag_id_1a562739",
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "reports.compare_flagcomparison"
                ),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CompareComponent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("component_id", models.TextField(max_length=100)),
                ("head_totals", models.JSONField(null=True)),
                ("base_totals", models.JSONField(null=True)),
                ("patch_totals", models.JSONField(null=True)),
                (
                    "commit_comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.comparecommit",
                    ),
                ),
            ],
            options={
                "db_table": "compare_componentcomparison",
                "indexes": [
                    shared.django_apps.reports.compare.LongIndex(
                        fields=["commit_comparison_id"],
                        name="compare_componentcomparison_commit_comparison_id_1c103280",
                    ),
                    models.Index(
                        fields=["commit_comparison_id", "component_id"],
                        name="component_comparison_component",
                    ),
                ],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "reports.compare_componentcomparison"
                ),
                models.Model,
            ),
        ),
        migrations.AddIndex(
            model_name="comparecommit",
            index=shared.django_apps.reports.compare.LongIndex(
                fields=["base_commit_id"],
                name="compare_commitcomparison_base_commit_id_cf53c1d9",
            ),
        ),
        migrations.AddIndex(
            model_name="comparecommit",
            index=shared.django_apps.reports.compare.LongIndex(
                fields=["compare_commit_id"],
                name="compare_commitcomparison_compare_commit_id_3ea19610",
            ),
        ),
        migrations.AddConstraint(
            model_name="comparecommit",
            constraint=models.UniqueConstraint(
                fields=("base_commit_id", "compare_commit_id"),
                name="unique_comparison_between_commit",
            ),
        ),
    ]
