# Generated by Django 4.2.16 on 2025-01-17 18:55

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAddIndex


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0036_upload_indices_part2"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="reportsession",
            index=models.Index(fields=["storage_path"], name="upload_storage_path_idx"),
        ),
    ]
