# Generated by Django 4.2.16 on 2025-01-16 16:34

from django.db import migrations, models

from shared.django_apps.migration_utils import RiskyAlterField


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0036_upload_indices_part2"),
    ]

    operations = [
        RiskyAlterField(
            model_name="reportsession",
            name="storage_path",
            field=models.TextField(null=True),
        ),
    ]
