# Generated by Django 4.2.16 on 2025-01-20 17:39

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRemoveConstraint


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0037_alter_reportsession_storage_path"),
    ]

    operations = [
        RiskyRemoveConstraint(
            model_name="test",
            name="reports_test_repoid_name_testsuite_flags_hash",
        ),
    ]
