# Generated by Django 4.2.16 on 2025-01-28 15:28

from django.db import migrations, models
from shared.django_apps.migration_utils import RiskyAddIndex

"""
BEGIN;
--
-- Create index upload_storage_path_idx on field(s) storage_path of model reportsession
--
CREATE INDEX "upload_storage_path_idx" ON "reports_upload" ("storage_path");
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0038_remove_test_reports_test_repoid_name_testsuite_flags_hash"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="reportsession",
            index=models.Index(fields=["storage_path"], name="upload_storage_path_idx"),
        ),
    ]
