# Generated by Django 4.2.16 on 2025-03-10 17:11

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("reports", "0039_reportsession_upload_storage_path_idx"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="testinstance",
            index=models.Index(fields=["repoid"], name="reports_tes_repoid_9cfd0a_idx"),
        ),
    ]
