# Generated by Django 4.2.16 on 2025-03-31 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0040_testinstance_reports_tes_repoid_9cfd0a_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportDetails",
        ),
    ]
