# Generated by Django 5.0.3 on 2024-03-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyOwner",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.owner",),
        ),
    ]
