# Generated by Django 4.2.13 on 2024-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    # BEGIN;
    # --
    # -- Create model UserOnboardingLifeCycleMetrics
    # --
    # CREATE TABLE "codecov_metrics_useronboardinglifecyclemetrics"
    # ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "org_id" integer NOT NULL, "event" text NOT NULL,
    # "timestamp" timestamp with time zone NOT NULL);
    # COMMIT;

    operations = [
        migrations.CreateModel(
            name="UserOnboardingLifeCycleMetrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("org_id", models.IntegerField()),
                ("event", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
