# Generated by Django 4.2.13 on 2024-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_metrics", "0001_initial"),
    ]
    # BEGIN;
    # --
    # -- Add field additional_data to useronboardinglifecyclemetrics
    # --
    # ALTER TABLE "codecov_metrics_useronboardinglifecyclemetrics" ADD COLUMN "additional_data" jsonb NULL;
    # COMMIT;

    operations = [
        migrations.AddField(
            model_name="useronboardinglifecyclemetrics",
            name="additional_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
