# Generated by Django 4.2.11 on 2024-04-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemetric',
            name='test_value_ts_telemetry',
            field=models.TextField(null=True),
        ),
    ]
