# Generated by Django 4.2.11 on 2024-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemetric',
            name='random_field_ts',
            field=models.TextField(null=True),
        ),
    ]
