# Generated by Django 4.2.16 on 2024-12-04 19:53

from django.db import migrations

from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("legacy_migrations", "0006_delete_many_owner_triggers"),
    ]

    operations = [
        RiskyRunSQL(
            """
            DROP TRIGGER IF EXISTS pulls_before_update_drop_flare ON pulls;
            DROP FUNCTION IF EXISTS pulls_drop_flare();
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
