# Generated by Django 4.2.11 on 2024-05-06 23:36

from django.db import migrations, models

from shared.django_apps.migration_utils import (
    RiskyAddField,
    RiskyAddIndex,
    RiskyRemoveField,
    RiskyRemoveIndex,
)


class Migration(migrations.Migration):

    dependencies = [
        ("user_measurements", "0001_initial"),
    ]

    operations = [
        RiskyRemoveIndex(
            model_name="usermeasurement",
            name="i_owner",
        ),
        RiskyRemoveIndex(
            model_name="usermeasurement",
            name="owner_repo",
        ),
        RiskyRemoveIndex(
            model_name="usermeasurement",
            name="owner_private_repo",
        ),
        RiskyRemoveIndex(
            model_name="usermeasurement",
            name="owner_private_repo_report_type",
        ),
        RiskyRemoveField(
            model_name="usermeasurement",
            name="commit",
        ),
        RiskyRemoveField(
            model_name="usermeasurement",
            name="owner",
        ),
        RiskyRemoveField(
            model_name="usermeasurement",
            name="repo",
        ),
        RiskyRemoveField(
            model_name="usermeasurement",
            name="upload",
        ),
        RiskyAddField(
            model_name="usermeasurement",
            name="commit_id",
            field=models.IntegerField(null=True),
        ),
        RiskyAddField(
            model_name="usermeasurement",
            name="owner_id",
            field=models.IntegerField(null=True),
        ),
        RiskyAddField(
            model_name="usermeasurement",
            name="repo_id",
            field=models.IntegerField(null=True),
        ),
        RiskyAddField(
            model_name="usermeasurement",
            name="upload_id",
            field=models.IntegerField(null=True),
        ),
        RiskyAddIndex(
            model_name="usermeasurement",
            index=models.Index(fields=["owner_id"], name="i_owner"),
        ),
        RiskyAddIndex(
            model_name="usermeasurement",
            index=models.Index(fields=["owner_id", "repo_id"], name="owner_repo"),
        ),
        RiskyAddIndex(
            model_name="usermeasurement",
            index=models.Index(
                fields=["owner_id", "private_repo"], name="owner_private_repo"
            ),
        ),
        RiskyAddIndex(
            model_name="usermeasurement",
            index=models.Index(
                fields=["owner_id", "private_repo", "report_type", "created_at"],
                name="owner_repo_report_created_at",
            ),
        ),
    ]
