# Generated by Django 4.2.11 on 2024-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeasurement',
            name='random_col',
            field=models.CharField(choices=[('coverage', 'Coverage'), ('test_results', 'Test Results'), ('bundle_analysis', 'Bundle Analysis')], max_length=100, null=True),
        ),
    ]
