# Generated by Django 4.2.13 on 2024-07-19 20:21

from django.db import migrations, models

"""
BEGIN;
--
-- Alter field upload_id on usermeasurement
--
ALTER TABLE "user_measurements" ALTER COLUMN "upload_id" TYPE bigint USING "upload_id"::bigint;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("user_measurements", "0002_remove_usermeasurement_i_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeasurement",
            name="upload_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
