# Generated by Django 4.2.7 on 2024-02-26 18:57

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models

import shared.django_apps.rollouts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    # BEGIN;
    # --
    # -- Create model FeatureFlag
    # --
    # CREATE TABLE "feature_flags" ("name" varchar(200) NOT NULL PRIMARY KEY, "proportion" decimal NOT NULL, "salt" varchar(32) NOT NULL);
    # --
    # -- Create model FeatureFlagVariant
    # --
    # CREATE TABLE "feature_flag_variants" ("variant_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(200) NOT NULL, "proportion" decimal NOT NULL, "value" text NOT NULL CHECK ((JSON_VALID("value") OR "value" IS NULL)), "override_owner_ids" integer[] NOT NULL, "override_repo_ids" integer[] NOT NULL, "feature_flag_id" varchar(200) NOT NULL REFERENCES "feature_flags" ("name") DEFERRABLE INITIALLY DEFERRED);
    # CREATE INDEX "feature_flag_variants_feature_flag_id_fa3a4c02" ON "feature_flag_variants" ("feature_flag_id");
    # CREATE INDEX "feature_fla_feature_15a078_idx" ON "feature_flag_variants" ("feature_flag_id");
    # COMMIT;

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "proportion",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                (
                    "salt",
                    models.CharField(
                        default=shared.django_apps.rollouts.models.default_random_salt,
                        max_length=32,
                    ),
                ),
            ],
            options={
                "db_table": "feature_flags",
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagVariant",
            fields=[
                ("variant_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "proportion",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("value", models.JSONField(default=False)),
                (
                    "override_owner_ids",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "override_repo_ids",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "feature_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="rollouts.featureflag",
                    ),
                ),
            ],
            options={
                "db_table": "feature_flag_variants",
                "indexes": [
                    models.Index(
                        fields=["feature_flag"], name="feature_fla_feature_15a078_idx"
                    )
                ],
            },
        ),
    ]
