# Generated by Django 4.2.7 on 2024-02-21 20:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import shared.django_apps.rollouts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    # BEGIN;
    # --
    # -- Create model FeatureFlag
    # --
    # CREATE TABLE "feature_flags" ("name" varchar(200) NOT NULL PRIMARY KEY, "proportion" decimal NOT NULL, "salt" varchar(10000) NOT NULL);
    # --
    # -- Create model FeatureFlagVariant
    # --
    # CREATE TABLE "feature_flag_variants" ("name" varchar(200) NOT NULL PRIMARY KEY, "proportion" decimal NOT NULL, "enabled" bool NOT NULL, "override_owner_ids" integer[] NOT NULL, "override_repo_ids" integer[] NOT NULL, "feature_flag_id" varchar(200) NOT NULL REFERENCES "feature_flags" ("name") DEFERRABLE INITIALLY DEFERRED);
    # --
    # -- Create constraint feature_flag_name on model featureflag
    # --
    # CREATE TABLE "new__feature_flags" ("name" varchar(200) NOT NULL PRIMARY KEY, "proportion" decimal NOT NULL, "salt" varchar(10000) NOT NULL, CONSTRAINT "feature_flag_name" UNIQUE ("name"));
    # INSERT INTO "new__feature_flags" ("name", "proportion", "salt") SELECT "name", "proportion", "salt" FROM "feature_flags";
    # DROP TABLE "feature_flags";
    # ALTER TABLE "new__feature_flags" RENAME TO "feature_flags";
    # CREATE INDEX "feature_flag_variants_feature_flag_id_fa3a4c02" ON "feature_flag_variants" ("feature_flag_id");
    # --
    # -- Create index feature_fla_feature_15a078_idx on field(s) feature_flag of model featureflagvariant
    # --
    # CREATE INDEX "feature_fla_feature_15a078_idx" ON "feature_flag_variants" ("feature_flag_id");
    # --
    # -- Create constraint feature_flag_variant_name on model featureflagvariant
    # --
    # CREATE TABLE "new__feature_flag_variants" ("name" varchar(200) NOT NULL PRIMARY KEY, "proportion" decimal NOT NULL, "enabled" bool NOT NULL, "override_owner_ids" integer[] NOT NULL, "override_repo_ids" integer[] NOT NULL, "feature_flag_id" varchar(200) NOT NULL REFERENCES "feature_flags" ("name") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "feature_flag_variant_name" UNIQUE ("name"));
    # INSERT INTO "new__feature_flag_variants" ("name", "proportion", "enabled", "override_owner_ids", "override_repo_ids", "feature_flag_id") SELECT "name", "proportion", "enabled", "override_owner_ids", "override_repo_ids", "feature_flag_id" FROM "feature_flag_variants";
    # DROP TABLE "feature_flag_variants";
    # ALTER TABLE "new__feature_flag_variants" RENAME TO "feature_flag_variants";
    # CREATE INDEX "feature_flag_variants_feature_flag_id_fa3a4c02" ON "feature_flag_variants" ("feature_flag_id");
    # CREATE INDEX "feature_fla_feature_15a078_idx" ON "feature_flag_variants" ("feature_flag_id");
    # COMMIT;

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "proportion",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                (
                    "salt",
                    models.CharField(
                        default=shared.django_apps.rollouts.models.default_random_salt,
                        max_length=10000,
                    ),
                ),
            ],
            options={
                "db_table": "feature_flags",
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagVariant",
            fields=[
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "proportion",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "override_owner_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "override_repo_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "feature_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="rollouts.featureflag",
                    ),
                ),
            ],
            options={
                "db_table": "feature_flag_variants",
            },
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.UniqueConstraint(
                fields=("name",), name="feature_flag_name"
            ),
        ),
        migrations.AddIndex(
            model_name="featureflagvariant",
            index=models.Index(
                fields=["feature_flag"], name="feature_fla_feature_15a078_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflagvariant",
            constraint=models.UniqueConstraint(
                fields=("name",), name="feature_flag_variant_name"
            ),
        ),
    ]
