# Generated by Django 4.2.7 on 2024-02-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollouts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="featureflagowneroverride",
            old_name="variants",
            new_name="variant",
        ),
        migrations.AddIndex(
            model_name="featureflagowneroverride",
            index=models.Index(
                fields=["feature"], name="feature_fla_feature_5a743d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureflagowneroverride",
            index=models.Index(
                fields=["variant"], name="feature_fla_variant_5662a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureflagrepooverride",
            index=models.Index(
                fields=["feature"], name="feature_fla_feature_2419b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureflagrepooverride",
            index=models.Index(
                fields=["variant"], name="feature_fla_variant_416b5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="featureflagvariant",
            index=models.Index(
                fields=["feature_flag"], name="feature_fla_feature_15a078_idx"
            ),
        ),
    ]
