# Generated by Django 4.2.7 on 2024-02-26 18:58

from django.db import migrations


def seed_initial_features(apps, schema_editor):
    FeatureFlag = apps.get_model("rollouts", "FeatureFlag")
    FeatureFlagVariant = apps.get_model("rollouts", "FeatureFlagVariant")

    list_repos_generator = FeatureFlag.objects.create(
        name="list_repos_generator", proportion=0.0
    )
    FeatureFlagVariant.objects.create(
        name="enabled",
        feature_flag=list_repos_generator,
        proportion=1.0,
        value=True,
    )

    use_label_index_in_report_processing = FeatureFlag.objects.create(
        name="use_label_index_in_report_processing", proportion=0.0
    )
    FeatureFlagVariant.objects.create(
        name="enabled",
        feature_flag=use_label_index_in_report_processing,
        proportion=1.0,
        value=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("rollouts", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_initial_features)]
