# Generated by Django 4.2.7 on 2024-02-21 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollouts", "0002_rename_variants_featureflagowneroverride_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featureflagrepooverride",
            name="feature",
        ),
        migrations.RemoveField(
            model_name="featureflagrepooverride",
            name="variant",
        ),
        migrations.AddField(
            model_name="featureflagvariant",
            name="override_owner_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="featureflagvariant",
            name="override_repo_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.DeleteModel(
            name="FeatureFlagOwnerOverride",
        ),
        migrations.DeleteModel(
            name="FeatureFlagRepoOverride",
        ),
    ]
