# Generated by Django 5.0.2 on 2024-03-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollouts", "0002_auto_20240226_1858"),
    ]

    # BEGIN;
    # --
    # -- Create model FeatureExposure
    # --
    # CREATE TABLE "rollouts_featureexposure" ("exposure_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "owner" integer NULL, "repo" integer NULL, "timestamp" timestamp with time zone NOT NULL, "feature_flag_id" varchar(200) NOT NULL, "feature_flag_variant_id" integer NOT NULL);
    # ALTER TABLE "rollouts_featureexposure" ADD CONSTRAINT "rollouts_featureexpo_feature_flag_id_5e4521fe_fk_feature_f" FOREIGN KEY ("feature_flag_id") REFERENCES "feature_flags" ("name") DEFERRABLE INITIALLY DEFERRED;
    # ALTER TABLE "rollouts_featureexposure" ADD CONSTRAINT "rollouts_featureexpo_feature_flag_variant_2a873986_fk_feature_f" FOREIGN KEY ("feature_flag_variant_id") REFERENCES "feature_flag_variants" ("variant_id") DEFERRABLE INITIALLY DEFERRED;
    # CREATE INDEX "rollouts_featureexposure_feature_flag_id_5e4521fe" ON "rollouts_featureexposure" ("feature_flag_id");
    # CREATE INDEX "rollouts_featureexposure_feature_flag_id_5e4521fe_like" ON "rollouts_featureexposure" ("feature_flag_id" varchar_pattern_ops);
    # CREATE INDEX "rollouts_featureexposure_feature_flag_variant_id_2a873986" ON "rollouts_featureexposure" ("feature_flag_variant_id");
    # COMMIT;

    operations = [
        migrations.CreateModel(
            name="FeatureExposure",
            fields=[
                ("exposure_id", models.AutoField(primary_key=True, serialize=False)),
                ("owner", models.IntegerField(blank=True, null=True)),
                ("repo", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "feature_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="rollouts.featureflag",
                    ),
                ),
                (
                    "feature_flag_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="rollouts.featureflagvariant",
                    ),
                ),
            ],
        ),
    ]
