# Generated by Django 4.2.7 on 2024-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollouts", "0002_auto_20240226_1858"),
    ]

    # BEGIN;
    # --
    # -- Alter field proportion on featureflag
    # --
    # -- (no-op)
    # --
    # -- Alter field proportion on featureflagvariant
    # --
    # -- (no-op)
    # --
    # -- Alter field value on featureflagvariant
    # --
    # -- (no-op)
    # COMMIT;

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="proportion",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Values are between 0 and 1. Eg: 0.5 means 50% of users",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="featureflagvariant",
            name="proportion",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Values are between 0 and 1. Eg: 0.5 means 50% of users. The sum of all variants' proportions for a feature should equal to 1.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="featureflagvariant",
            name="value",
            field=models.JSONField(
                default=False,
                help_text="Accepts JSON values. Eg: `true`, `false`, `10`, `['abc', 'def']`, `{'k': 'v'}`",
            ),
        ),
    ]
