# Generated by Django 4.2.11 on 2024-04-29 15:12

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollouts", "0004_featureexposure"),
    ]

    # BEGIN;
    # --
    # -- Create model FeatureExposure
    # --
    # CREATE TABLE "feature_exposures" ("exposure_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "owner" integer NULL, "repo" integer NULL, "timestamp" timestamp with time zone NOT NULL, "feature_flag_id" varchar(200) NOT NULL, "feature_flag_variant_id" integer NOT NULL);
    # ALTER TABLE "feature_exposures" ADD CONSTRAINT "feature_exposures_feature_flag_id_628f8212_fk_feature_f" FOREIGN KEY ("feature_flag_id") REFERENCES "feature_flags" ("name") DEFERRABLE INITIALLY DEFERRED;
    # ALTER TABLE "feature_exposures" ADD CONSTRAINT "feature_exposures_feature_flag_variant_bfb854ff_fk_feature_f" FOREIGN KEY ("feature_flag_variant_id") REFERENCES "feature_flag_variants" ("variant_id") DEFERRABLE INITIALLY DEFERRED;
    # CREATE INDEX "feature_exposures_feature_flag_id_628f8212" ON "feature_exposures" ("feature_flag_id");
    # CREATE INDEX "feature_exposures_feature_flag_id_628f8212_like" ON "feature_exposures" ("feature_flag_id" varchar_pattern_ops);
    # CREATE INDEX "feature_exposures_feature_flag_variant_id_bfb854ff" ON "feature_exposures" ("feature_flag_variant_id");
    # COMMIT;

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="platform",
            field=models.CharField(
                choices=[("F", "Frontend"), ("B", "Backend")], default="B", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="rollout_identifier",
            field=models.CharField(
                choices=[
                    ("U", "Owner ID"),
                    ("R", "Repo ID"),
                    ("O", "Org ID"),
                    ("E", "Email"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="featureflagvariant",
            name="override_emails",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="featureflagvariant",
            name="override_org_ids",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
