# Generated by Django 4.2.11 on 2024-04-29 15:12

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollouts", "0004_featureexposure"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="platform",
            field=models.CharField(
                choices=[("F", "Frontend"), ("B", "Backend")], default="B", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="rollout_identifier",
            field=models.CharField(
                choices=[
                    ("U", "Owner ID"),
                    ("R", "Repo ID"),
                    ("O", "Org ID"),
                    ("E", "Email"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="featureflagvariant",
            name="override_emails",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="featureflagvariant",
            name="override_org_ids",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
