# Generated by Django 4.2.16 on 2025-03-12 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rollouts", "0005_featureflag_is_active_featureflag_platform_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeatureExposure",
        ),
    ]
